// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	OnlineRequest
	OnlineReply
	InterOnlineRequest
	InterOnlineReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// master - client communication
type OnlineRequest struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *OnlineRequest) Reset()                    { *m = OnlineRequest{} }
func (m *OnlineRequest) String() string            { return proto.CompactTextString(m) }
func (*OnlineRequest) ProtoMessage()               {}
func (*OnlineRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OnlineRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type OnlineReply struct {
	Servers []*OnlineReply_Online `protobuf:"bytes,1,rep,name=servers" json:"servers,omitempty"`
	Total   uint32                `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (m *OnlineReply) Reset()                    { *m = OnlineReply{} }
func (m *OnlineReply) String() string            { return proto.CompactTextString(m) }
func (*OnlineReply) ProtoMessage()               {}
func (*OnlineReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OnlineReply) GetServers() []*OnlineReply_Online {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *OnlineReply) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type OnlineReply_Online struct {
	Id    string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *OnlineReply_Online) Reset()                    { *m = OnlineReply_Online{} }
func (m *OnlineReply_Online) String() string            { return proto.CompactTextString(m) }
func (*OnlineReply_Online) ProtoMessage()               {}
func (*OnlineReply_Online) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *OnlineReply_Online) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OnlineReply_Online) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// master - servers communication
type InterOnlineRequest struct {
}

func (m *InterOnlineRequest) Reset()                    { *m = InterOnlineRequest{} }
func (m *InterOnlineRequest) String() string            { return proto.CompactTextString(m) }
func (*InterOnlineRequest) ProtoMessage()               {}
func (*InterOnlineRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type InterOnlineReply struct {
	Count uint32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *InterOnlineReply) Reset()                    { *m = InterOnlineReply{} }
func (m *InterOnlineReply) String() string            { return proto.CompactTextString(m) }
func (*InterOnlineReply) ProtoMessage()               {}
func (*InterOnlineReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InterOnlineReply) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*OnlineRequest)(nil), "pb.OnlineRequest")
	proto.RegisterType((*OnlineReply)(nil), "pb.OnlineReply")
	proto.RegisterType((*OnlineReply_Online)(nil), "pb.OnlineReply.Online")
	proto.RegisterType((*InterOnlineRequest)(nil), "pb.InterOnlineRequest")
	proto.RegisterType((*InterOnlineReply)(nil), "pb.InterOnlineReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Online service

type OnlineClient interface {
	OnlineStatistics(ctx context.Context, in *OnlineRequest, opts ...grpc.CallOption) (*OnlineReply, error)
	InterOnline(ctx context.Context, in *InterOnlineRequest, opts ...grpc.CallOption) (*InterOnlineReply, error)
}

type onlineClient struct {
	cc *grpc.ClientConn
}

func NewOnlineClient(cc *grpc.ClientConn) OnlineClient {
	return &onlineClient{cc}
}

func (c *onlineClient) OnlineStatistics(ctx context.Context, in *OnlineRequest, opts ...grpc.CallOption) (*OnlineReply, error) {
	out := new(OnlineReply)
	err := grpc.Invoke(ctx, "/pb.Online/OnlineStatistics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onlineClient) InterOnline(ctx context.Context, in *InterOnlineRequest, opts ...grpc.CallOption) (*InterOnlineReply, error) {
	out := new(InterOnlineReply)
	err := grpc.Invoke(ctx, "/pb.Online/InterOnline", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Online service

type OnlineServer interface {
	OnlineStatistics(context.Context, *OnlineRequest) (*OnlineReply, error)
	InterOnline(context.Context, *InterOnlineRequest) (*InterOnlineReply, error)
}

func RegisterOnlineServer(s *grpc.Server, srv OnlineServer) {
	s.RegisterService(&_Online_serviceDesc, srv)
}

func _Online_OnlineStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineServer).OnlineStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Online/OnlineStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineServer).OnlineStatistics(ctx, req.(*OnlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Online_InterOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterOnlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineServer).InterOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Online/InterOnline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineServer).InterOnline(ctx, req.(*InterOnlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Online_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Online",
	HandlerType: (*OnlineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnlineStatistics",
			Handler:    _Online_OnlineStatistics_Handler,
		},
		{
			MethodName: "InterOnline",
			Handler:    _Online_InterOnline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x4d, 0xd5, 0x15, 0xa7, 0x54, 0xd7, 0xa1, 0x48, 0xe9, 0xa9, 0xc4, 0x4b, 0x4f, 0x45,
	0xd6, 0x8b, 0x17, 0x7f, 0x40, 0x4f, 0x42, 0xfd, 0x05, 0xed, 0xee, 0x20, 0x85, 0x9a, 0xc4, 0x64,
	0x56, 0xd8, 0xa3, 0x07, 0xff, 0xb7, 0x6c, 0x6a, 0x96, 0xac, 0x7b, 0x9b, 0x19, 0xbe, 0x97, 0xf7,
	0x5e, 0x20, 0xfb, 0x20, 0xe7, 0xfa, 0x77, 0x6a, 0x8c, 0xd5, 0xac, 0x31, 0x31, 0x83, 0x7c, 0x80,
	0xec, 0x55, 0x4d, 0xa3, 0xa2, 0x8e, 0x3e, 0xb7, 0xe4, 0x18, 0x11, 0x2e, 0x78, 0x67, 0xa8, 0x10,
	0x95, 0xa8, 0xaf, 0x3b, 0x3f, 0xcb, 0x1f, 0x01, 0x69, 0xa0, 0xcc, 0xb4, 0xc3, 0x47, 0xb8, 0x72,
	0x64, 0xbf, 0xc8, 0xba, 0x42, 0x54, 0xe7, 0x75, 0xba, 0xba, 0x6f, 0xcc, 0xd0, 0x44, 0x44, 0x98,
	0x03, 0x86, 0x39, 0x5c, 0xb2, 0xe6, 0x7e, 0x2a, 0x92, 0x4a, 0xd4, 0x59, 0x37, 0x2f, 0x65, 0x03,
	0x8b, 0x19, 0xc4, 0x1b, 0x48, 0xda, 0xcd, 0x9f, 0x67, 0xd2, 0x6e, 0xf6, 0xfc, 0x5a, 0x6f, 0x15,
	0x07, 0xde, 0x2f, 0x32, 0x07, 0x6c, 0x15, 0x93, 0x3d, 0x4a, 0x2c, 0x6b, 0x58, 0x1e, 0x5d, 0xf7,
	0x09, 0x0f, 0x7a, 0x11, 0xe9, 0x57, 0xdf, 0xe2, 0x60, 0xf8, 0x0c, 0xcb, 0x79, 0x7a, 0xe3, 0x9e,
	0x47, 0xc7, 0xe3, 0xda, 0xe1, 0x5d, 0xdc, 0xc2, 0xbf, 0x5d, 0xde, 0xfe, 0x2b, 0x26, 0xcf, 0xf0,
	0x05, 0xd2, 0xc8, 0x0e, 0x7d, 0xf5, 0xd3, 0x54, 0x65, 0x7e, 0x72, 0xf7, 0xf2, 0x61, 0xe1, 0xff,
	0xfe, 0xe9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x60, 0xc7, 0x7a, 0x90, 0x8c, 0x01, 0x00, 0x00,
}
